language: android

android:
  components:
    - build-tools-30.0.2

before_install:
    - yes | sdkmanager --licenses

language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-30.0.2
    - android-30
before_install:
  - yes | sdkmanager "platforms;android-30"
script:
   - ./gradlew build connectedCheck