language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - build-tools-30.0.2
    - android-30
before_install:
  - yes | sdkmanager "platforms;android-30"
